name: Android CI

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Install dependencies
      run: git submodule update --init --recursive
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: app/build/outputs
